name: Build storybook
description: Install dependencies and build Storybook
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
    - name: Install dependencies
      shell: bash
      run: npm ci --no-audit --prefer-offline --ignore-scripts
    - name: Build storybook
      shell: bash
      run: npm run build-storybook -- --quiet
