name: Publish package
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Publish to GitHub Packages
        uses: ./.github/actions/publish-package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
